"""create_stock_adjustments_table

Revision ID: 6b90e13f5c3d
Revises: 9d3411b2cbd0
Create Date: 2026-07-15 19:58:05.861997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b90e13f5c3d'
down_revision: Union[str, Sequence[str], None] = '9d3411b2cbd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_adjustments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("adjustment_type IN ('IN', 'OUT', 'ADJUSTMENT')", name='ck_stock_adjustments_type_valid'),
    sa.CheckConstraint('quantity != 0', name='ck_stock_adjustments_quantity_nonzero'),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_adjustments_business_id'), 'stock_adjustments', ['business_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_product_id'), 'stock_adjustments', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_adjustments_product_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_business_id'), table_name='stock_adjustments')
    op.drop_table('stock_adjustments')
    # ### end Alembic commands ###
